/**
 * 
 */
package com.afroware.blockchain.message;

/**
 * @author lamal
 *
 */
public enum MessageType {

	QUERY_LATEST(0),
	QUERY_ALL(1),
	RESPONSE_BLOCKCHAIN(2),
	QUERY_TRANSACTION_POOL(3),
	RESPONSE_TRANSACTION_POOL(4),
	PEER_CONNECT_REQUEST(5),
	PEER_CONNECT_REQUEST_ERROR(6), 
	PEER_CONNECT_RESPONSE_ERROR(7),
	PEER_CONNECT_RESPONSE(8),
	HELLO(100),
	RESPONSE_PEERS(9),
	RESPONSE_TRANSACTION(10),
	RESPONSE_ACCOUNT(11),
	RESPONSE_BALANCE(12),
	RESPONSE_BALANCE_ERROR(13),
	RESPONSE_ACCOUNT_ERROR(14),
	RESPONSE_BLOCKCHAIN_ERROR(15), 
	RESPONSE_TRANSACTION_ERROR(16),
	QUERY_TRANSACTION_ERROR(17),
	QUERY_BLOCKCHAIN_ERROR(18);

	MessageType(int i) {
	}

}
